import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/slidebar/slidebar";
import Header from "./components/header/Header";
import "@fontsource/fira-sans/100.css";
import "@fontsource/fira-sans/200.css";
import "@fontsource/fira-sans/300.css";
import "@fontsource/fira-sans/400.css";
import "@fontsource/fira-sans/500.css";
import "@fontsource/fira-sans/600.css";
import "@fontsource/fira-sans/700.css";
import "@fontsource/fira-sans/800.css";

import "@fontsource/nunito/200.css";
import "@fontsource/nunito/300.css";
import "@fontsource/nunito/400.css";
import "@fontsource/nunito/500.css";
import "@fontsource/nunito/600.css";
import "@fontsource/nunito/700.css";
import "@fontsource/nunito/800.css";
import OpenIconSpeedDial from "./components/menu/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: "0", background: "#071D34" }}>
        <Box
          id="Container Sidebar"
          sx={{
            display: { xs: "none", sm: "block" },
            position: "fixed",
            top: 0,
            left: 0,
            height: "100vh",
            zIndex: 1300,
          }}
        >
          <Sidebar />
        </Box>
        <Box
          sx={{
            display: { sm: "none", xs: "block" },
            bottom: "10px",
            right: "10px",
            zIndex: 10,
            position: "fixed",
          }}
        >
          <OpenIconSpeedDial />
        </Box>
        <Box
          sx={{
            position: "fixed",
            top: 0,
            left: "263px",
            right: 0,
            zIndex: 1400,
          }}
        >
          <Header />
        </Box>
        <Box
          id={"container children layout"}
          sx={{
            marginTop: "64px",
            marginLeft: { sm: "265px" },
          }}
        >
          {children}
        </Box>
        +{" "}
      </body>
    </html>
  );
}
