name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
env:
  NEXT_PUBLIC_FIREBASE_APIKEY: ${{secrets.FIREBASE_APIKEY}}
  NEXT_PUBLIC_FIREBASE_AUTHDOMAIN: ${{secrets.FIREBASE_AUTHDOMAIN}}
  NEXT_PUBLIC_FIREBASE_PROJECTID: ${{secrets.FIREBASE_PROJECTID}}
  NEXT_PUBLIC_FIREBASE_STORAGEBUCKET: ${{secrets.FIREBASE_STORAGEBUCKET}}
  NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID: ${{secrets.FIREBASE_MESSAGINGSENDERID}}
  NEXT_PUBLIC_FIREBASE_APPID: ${{secrets.FIREBASE_APPID}}
  NEXT_PUBLIC_FIREBASE_MEASUREMENTID: ${{secrets.FIREBASE_MEASUREMENTID}}
  NEXT_PUBLIC_KEY_API_VERIFIK: ${{secrets.KEY_API_VERIFIK}}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean cache
        run: npm cache clear --force

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.HOSTING_DEPLOYMENT }}"
          channelId: live
          projectId: verifik-b217c
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
